### PR TITLE
Update runtime.js

### PR DESCRIPTION
**Pull request by brianmbutler**
Fixes regenerator.awrap errors.

### CODE REVIEW

**Comment by stefanpenner** [comment]
Woot

**Comment by brianmbutler** [comment]
The computed decorators is still throwing errors but I see there are issue chains for that already.

**Comment by stefanpenner** [comment]
Correct. I aim to address those shortly. Thanks for this pr

**Comment by stefanpenner** [comment]
I'll just merge. Since the tests will fail until the decorators are fixed

**Comment by brianmbutler** [comment]
NP.   Forked it to try to follow your component chain.

**Pull request merged**
